### ISSUE TITLE
Get error dispatcher not find

### ISSUE THREAD

**Issue by inromualdo** [AleksanderMielczarek/AndroidAnnotationsPermissionsDispatcherPlugin#7]
After updating to 2.0.0 i get error:
Error:(107, 9) error: cannot find symbol variable SplashActivityPermissionsDispatcher
in the generated class

**Comment by AleksanderMielczarek** [comment]
Hi,

can you provide more info including `build.gradle` and code of `SplashActivity`?

**Comment by inromualdo** [comment]
Hi. Thank you for answer. I have this issues for all activies where i'm using permission dispatcher.
The issues are in the generated class.
build.gradle
```
def AAVersion = '4.3.1'
def PDVersion = '2.4.0'

 compile "com.github.hotchemi:permissionsdispatcher:$PDVersion"
 annotationProcessor "com.github.hotchemi:permissionsdispatcher-processor:$PDVersion"
 
 compile "org.androidannotations:androidannotations-api:$AAVersion"
 annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
 annotationProcessor 'com.github.AleksanderMielczarek:AndroidAnnotationsPermissionsDispatcherPlugin:2.0.0'
```

SplashActivity

```
@EActivity
@RuntimePermissions
public class SplashActivity extends AppCompatActivity implements GoogleApiClient.ConnectionCallbacks, GoogleApiClient.OnConnectionFailedListener, OnSuccessListener<Location>, OnFailureListener {
...
@NeedsPermission({android.Manifest.permission.ACCESS_COARSE_LOCATION, android.Manifest.permission.ACCESS_FINE_LOCATION})
    void getLastLocation(){
        Log.d(TAG, "getLastLocation: ");
        if (ActivityCompat.checkSelfPermission(this, android.Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(this, android.Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            // TODO: Consider calling
            //    ActivityCompat#requestPermissions
            // here to request the missing permissions, and then overriding
            //   public void onRequestPermissionsResult(int requestCode, String[] permissions,
            //                                          int[] grantResults)
            // to handle the case where the user grants the permission. See the documentation
            // for ActivityCompat#requestPermissions for more details.
            return;
        }
        mFusedLocationClient.getLastLocation().addOnSuccessListener(this).addOnFailureListener(this);
    }
}
```

**Comment by AleksanderMielczarek** [comment]
I cannot reproduce this one but for me it looks like a problem with wrong package. I'm not sure if this is actual problem but have you tried to add following code to app level `build.gradle`?

```
android {

    //some stuff

    defaultConfig {

        //some stuff    
  
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["resourcePackageName": android.defaultConfig.applicationId]
            }
        }
    }
}
```

**Comment by inromualdo** [comment]
I reproduce it.
I create a new projet
projet level build gradle:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:3.1.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

allprojects {
    repositories {
       ...
        maven { url "https://www.jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

app level build gradle
```

apply plugin: 'com.android.application'
def AAVersion = '4.3.1'
def PDVersion = '2.4.0'
...

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    compile "com.github.hotchemi:permissionsdispatcher:$PDVersion"
    annotationProcessor "com.github.hotchemi:permissionsdispatcher-processor:$PDVersion"

    compile "org.androidannotations:androidannotations-api:$AAVersion"
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
    annotationProcessor "com.github.AleksanderMielczarek:AndroidAnnotationsPermissionsDispatcherPlugin:2.0.0"
....

```

MainActivity



```
@EActivity
public class MainActivity extends AppCompatActivity
        implements NavigationView.OnNavigationItemSelectedListener {

@Override
    protected void onCreate(Bundle savedInstanceState) {
       test();
   }


@NeedsPermission(Manifest.permission.ACCESS_FINE_LOCATION)
    void test(){
        Log.d(TAG, "test: ");
    }
}
```

And same error:
MainActivity_
```
public final class MainActivity_
    extends MainActivity
    implements HasViews
{
     @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);

        //////////ERROR HERE
        MainActivityPermissionsDispatcher.onRequestPermissionsResult(this, requestCode, grantResults);
        permissionDispatcherCalled_ = false;
    }

    @Override
    void test() {
        if (!permissionDispatcherCalled_) {
            permissionDispatcherCalled_ = true;
            //////////ERROR HERE
            MainActivityPermissionsDispatcher.testWithCheck(this);
        } else {
            permissionDispatcherCalled_ = false;
            MainActivity_.super.test();
        }
    }
}
```

**Comment by AleksanderMielczarek** [comment]
You forget about `@RuntimePermissions` on top of `MainActivity`. You also no longer need `apt` plugin. 

It would be helpful if you could create example project showing mentioned issue.

**Comment by inromualdo** [comment]
I use the code in the plugin example: It work but just execute `@OnNeverAskAgain` function.

**Comment by AleksanderMielczarek** [comment]
There is nothing I can do unless you provide example project that I could checkout to confirm issue.

**Comment by inromualdo** [comment]
I just create a new projet to provide example and everything work. I don't know why. I will check it again. Thank you.

**Comment by AleksanderMielczarek** [comment]
No problem 😃 Just post your investigation result here.

**Comment by inromualdo** [comment]
I reproduce the issues. In my projet i use DBFlow

this line:
    `annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"`
cause the error.
When i remove it every think work.

**Comment by AleksanderMielczarek** [comment]
I've just created another branch with DBFlow in dependencies and it's working fine. Please take a look.

https://github.com/AleksanderMielczarek/AndroidAnnotationsPermissionsDispatcherPlugin/tree/dbflow

**Comment by han361769045** [comment]
I reproduce it. 
Can not found   XXXXXPermissionsDispatcher class

**Comment by AleksanderMielczarek** [comment]
Hello @han361769045. Can you provide link to repo with sample project showing error?

**Comment by han361769045** [comment]
this link
https://github.com/han361769045/TestAAPDP

**Comment by AleksanderMielczarek** [comment]
Thank you @han361769045. I'll check it later.

**Comment by AleksanderMielczarek** [comment]
@han361769045, @inromualdo TestAAPDP project is working for me, WelcomeActivityPermissionsDispatcher is generated,

What OS and Java version are you using?

**Comment by han361769045** [comment]
mac v10.12.5
java v1.8.0_121

**Comment by han361769045** [comment]
![wechatimg73](https://user-images.githubusercontent.com/8857329/28650838-dfc4cfca-72b0-11e7-8ce7-e223f5e21fca.jpeg)

**Comment by WonderCsabo** [comment]
@AleksanderMielczarek unfortunately i am also seeing the problem. I think the root cause is that the order of the annotation processors is random. In the worst case, the AndroidAnnotations processor runs first, which claims the `@RuntimePermissions` annotation. The PermissionDispatcher processor then could be called second, but the annotation was already claimed, so it does not run.

**Comment by AleksanderMielczarek** [comment]
@WonderCsabo thank you for explanation!

**Comment by AleksanderMielczarek** [comment]
@inromualdo @han361769045 @WonderCsabo fixed in 2.0.1
